interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice: number;
  description: string;
  discount: number;
  image: string;
  image1: string;
  image2: string;
  image3: string;
  category: 'iphone' | 'playstation' | 'macbook';
  stock: number;
  features: string[];
}

export const products: Product[] = [
  // iPhone Category
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    price: 1099.99,
    originalPrice: 1299.99,
    description: 'The most powerful iPhone ever with revolutionary A18 Pro chip',
    discount: 15,
    image: '/images/iphones/iphone_16_pro_max/iphone_16_pro_max_1.jpg',
    image1: '/images/iphones/iphone_16_pro_max/iphone_16_pro_max_2.jpg',
    image2: '/images/iphones/iphone_16_pro_max/iphone_16_pro_max_3.jpg',
    image3: '/images/iphones/iphone_16_pro_max/iphone_16_pro_max_4.jpg',
    category: 'iphone',
    stock: 50,
    features: ['6.9" Super Retina XDR display', 'A18 Pro chip', '1TB storage', 'Titanium design']
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    price: 999.99,
    originalPrice: 1199.99,
    description: 'Pro camera system for mind-blowing shots',
    discount: 17,
    image: '/images/iphones/iphone-16-pro/iphone-16-pro-1.webp',
    image1: '/images/iphones/iphone-16-pro/iphone-16-pro-2.webp',
    image2: '/images/iphones/iphone-16-pro/iphone-16-pro-3.webp',
    image3: '/images/iphones/iphone-16-pro/iphone-16-pro-4.webp',
    category: 'iphone',
    stock: 75,
    features: ['6.7" Super Retina XDR display', 'A18 Pro chip', '512GB storage', 'Pro camera system']
  },
  {
    id: 'iphone-16-plus',
    name: 'iPhone 16 Plus',
    price: 899.99,
    originalPrice: 999.99,
    description: 'Big beautiful display with all-day battery life',
    discount: 10,
    image: '/images/iphones/iphone-16-plus/apple-iphone-16-plus-1.jpg',
    image1: '/images/iphones/iphone-16-plus/apple-iphone-16-plus-2.jpg',
    image2: '/images/iphones/iphone-16-plus/apple-iphone-16-plus-3.jpg',
    image3: '/images/iphones/iphone-16-plus/apple-iphone-16-plus-4.jpg',
    category: 'iphone',
    stock: 100,
    features: ['6.7" Super Retina display', 'A18 chip', '256GB storage', 'Dual camera']
  },
  {
    id: 'iphone-16',
    name: 'iPhone 16',
    price: 799.99,
    originalPrice: 899.99,
    description: 'The perfect iPhone for everyone',
    discount: 11,
    image: '/images/iphones/iphone-16/iphone-16-1.jpg',
    image1: '/images/iphones/iphone-16/iphone-16-2.jpg',
    image2: '/images/iphones/iphone-16/iphone-16-3.jpg',
    image3: '/images/iphones/iphone-16/iphone-16-4.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.1" Super Retina display', 'A18 chip', '128GB storage', 'All-day battery']
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    price: 350.99,
    originalPrice: 450.99,
    description: 'Unlocked for freedom to choose your carrier. Compatible with both GSM & CDMA networks. The phone is unlocked to work with all GSM Carriers & CDMA Carriers Including AT&T, T-Mobile, Verizon, Sprint., Etc',
    discount: 11,
    image: '/images/iphones/iphone-15/iphone-15-1.webp',
    image1: '/images/iphones/iphone-15/iphone-15-2.webp',
    image2: '/images/iphones/iphone-15/iphone-15-3.webp',
    image3: '/images/iphones/iphone-15/iphone-15-4.webp',
    category: 'iphone',
    stock: 150,
    features: ['6.1" Super Retina XDR OLED', 'HDR10', 'Dolby Vision', '1000 nits (HBM)','3349mAh Battery','128GB 6GB']
  },
  {
    id: 'iphone-15-plus',
    name: 'iPhone 15 plus',
    price: 700.99,
    originalPrice: 852.99,
    description: 'iPhone 15 plus features a durable colour-infused glass and aluminium design. It’s splash, water and dust resistant.1 The Ceramic Shield front is super-tough. And the 6.7” Super Retina XDR display2 is up to 2x brighter in the sun compared to iPhone 14',
    discount: 11,
    image: '/images/iphones/iphone-15-plus/iPhone_15_Plus_Green_PDP_Image_Position-1_alt__en-IN.jpg',
    image1: '/images/iphones/iphone-15-plus/iPhone_15_Plus_Green_PDP_Image_Position-1__en-IN.jpg',
    image2: '/images/iphones/iphone-15-plus/iPhone_15_Plus_Green_PDP_Image_Position-2__en-IN.jpg',
    image3: '/images/iphones/iphone-15-plus/iPhone_15_Plus_Green_PDP_Image_Position-3__en-IN.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.7” Super Retina XDR display2', 'Ceramic Shield front', '48MP MAIN CAMERA WITH 2X TELEPHOTO', '1000 nits (HBM)','3349mAh Battery','128GB 6GB']
  },
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 pro',
    price: 900.99,
    originalPrice: 1013.29,
    description: 'The iPhone 15 Pro features an aerospace‑grade titanium design with an all‑new Action button to fast track to your favorite feature. The powerful camera system offers multiple focal lengths for super‑high‑resolution photos with a new level of detail and color.',
    discount: 11,
    image: '/images/iphones/iphone-15-pro/iPhone_15_Pro_Natural_Titanium_PDP_Image_Position-1_alt__en-IN.jpg',
    image1: '/images/iphones/iphone-15-pro/iPhone_15_Pro_Natural_Titanium_PDP_Image_Position-1__en-IN.jpg',
    image2: '/images/iphones/iphone-15-pro/iPhone_15_Pro_Natural_Titanium_PDP_Image_Position-2__en-IN.jpg',
    image3: '/images/iphones/iphone-15-pro/iPhone_15_Pro_Natural_Titanium_PDP_Image_Position-3__en-IN.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.1” Super Retina XDR display', 'ProMotion Technology', 'Megapowerful 48MP camera', ' 3x optical zoom and 15x digital zoom','Up to 23 hours video playback','Facetime is available']
  },
  {
    id: 'iphone-14',
    name: 'iPhone 14',
    price: 476.99,
    originalPrice: 586.99,
    description: 'iPhone 14 offers Vital safety features—Emergency SOS via satellite and Crash Detection with Industry-leading durability features with Ceramic Shield and water resistance',
    discount: 11,
    image: '/images/iphones/iphone-14/iPhone_14_Starlight_PDP_Image_Position-1B__WWEN_a6501dcd-195a-4f4f-b3b7-86244f02e5b8.jpg',
    image1: '/images/iphones/iphone-14/iPhone_14_Starlight_PDP_Image_Position-1A__WWEN_d53da00d-03ea-40db-8c13-08227bfb5e3a.jpg',
    image2: '/images/iphones/iphone-14/iPhone_14_Starlight_PDP_Image_Position-2__WWEN_1300817b-8ceb-4aef-9b84-d8d5fe5b64f8.jpg',
    image3: '/images/iphones/iphone-14/iPhone_14_Starlight_PDP_Image_Position-3__WWEN_49138210-1066-4514-87d3-6ebda6cd52f4.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.1-inch Super Retina XDR display', 'Advanced camera system for better photos in any light', 'Cinematic mode now in 4K Dolby Vision up to 30 fps ', ' Action mode for smooth, steady, handheld videos','Up to 23 hours video playback','Facetime is available']
  },
  {
    id: 'iphone-14-plus',
    name: 'iPhone 14 plus',
    price: 500.99,
    originalPrice: 639.99,
    description: 'Meet iPhone 14 Plus. With Crash Detection. Longer battery life than ever. And even more spectacular low-light shots. All in five great colors.',
    discount: 11,
    image: '/images/iphones/iphone-14-plus/iPhone_14_Plus_Blue_PDP_Image_Position-1B__WWEN_6c5b3bfe-9097-4144-a832-1508311a938d.jpg',
    image1: '/images/iphones/iphone-14-plus/iPhone_14_Plus_Blue_PDP_Image_Position-1A__WWEN_20fc3205-e675-4d4e-88d8-8cb06e5ccded.jpg',
    image2: '/images/iphones/iphone-14-plus/iPhone_14_Plus_Blue_PDP_Image_Position-2__WWEN_fb3157b2-5ae9-4468-8c4b-77b64a38048c.jpg',
    image3: '/images/iphones/iphone-14-plus/iPhone_14_Plus_Blue_PDP_Image_Position-3__WWEN_3c78aed1-f8c4-4b74-94db-e4f6c9721358.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.7-inch Super Retina XDR display ', 'Advanced camera system for better photos in any light', 'Cinematic mode now in 4K Dolby Vision up to 30 fps ', ' Action mode for smooth, steady, handheld videos','All-day battery life and up to 26 hours of video playback','A15 Bionic chip with 5-core GPU for lightning-fast performance. Superfast 5G cellular ']
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 pro',
    price: 610.99,
    originalPrice: 711.99,
    description: 'The iPhone 14 pro features a 6.1-inch Super Retina XDR display with ProMotion technology, an "Always-On" display, and a "Dynamic Island" that replaces the traditional notch. It also boasts a pro camera system with a 48MP main camera, 12MP ultra wide, and 12MP telephoto lenses. The iPhone 14 Pro is powered by the A16 Bionic chip and includes advanced safety features like Crash Detection',
    discount: 11,
    image: '/images/iphones/iphone-14-pro/iPhone_14_Blue_PDP_Image_Position-1A__WWEN.jpg',
    image1: '/images/iphones/iphone-14-pro/iPhone_14_Blue_PDP_Image_Position-1B__WWEN.jpg',
    image2: '/images/iphones/iphone-14-pro/iPhone_14_Blue_PDP_Image_Position-2__WWEN.jpg',
    image3: '/images/iphones/iphone-14-pro/iPhone_14_Blue_PDP_Image_Position-3__WWEN.jpg',
    category: 'iphone',
    stock: 150,
    features: ['Super Retina XDR OLED, 6.1 inches ', 'A16 Bionic chip', 'Triple 12MP system: Ultra Wide, Wide, Telephoto', ' 12MP TrueDepth Camera FrontCameraa','All-day battery life and up to 26 hours of video playback','A15 Bionic chip with 5-core GPU for lightning-fast performance. Superfast 5G cellular ']
  },

  // PlayStation 5 Category
  {
    id: 'PlayStation-5-Slim-Digital-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty',
    name: "PlayStation 5 Slim Digital Edition Console (KSA version), 2 Year Manufacturer Warranty ",
    price: 429.99,
    originalPrice: 529.99,
    description: 'Slim Design - With PS5 Digital Console, players get powerful gaming technology packed inside a sleek and compact console design.',
    discount: 20,
    image: '/images/playstation/PlayStation-5-Slim-Digital-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty/PlayStation-5-Slim-Digital-Edition-1.jpg',
    image1: '/images/playstation/PlayStation-5-Slim-Digital-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty/PlayStation-5-Slim-Digital-Edition-2.jpg',
    image2: '/images/playstation/PlayStation-5-Slim-Digital-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty/PlayStation-5-Slim-Digital-Edition-3.jpg',
    image3: '/images/playstation/PlayStation-5-Slim-Digital-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty/PlayStation-5-Slim-Digital-Edition-4.jpg',
    category: 'playstation',
    stock: 45,
    features: ['Slim Design - With PS5 Digital Console, players get powerful gaming technology packed inside a sleek and compact console design. ', '1TB of Storage - Keep your favorite games ready and waiting for you to jump in and play with 1TB of SSD storage built in. ', 'Box Contents - 1 DualSense Wireless Controller, 2 Horizontal Stand Feet, HDMI Cable, AC Power Cord, USB cable, printed materials,', 'PS5 console (CFI-2000 model group – slim). Vertical Stand sold separately.']
  },
  {
    id: 'PlayStation-5-Slim-Blu-ray-Disc-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty',
    name: 'PlayStation 5 Slim Blu-ray Disc Edition Console (KSA version), 2 Year Manufacturer Warranty',
    price: 449.99,
    originalPrice: 549.99,
    description: ' Slim Design - With PS5 Disc Console, players get powerful gaming technology packed inside a sleek and compact console design. ',
    discount: 18,
    image: '/images/playstation/PlayStation-5-Slim-Blu-ray-Disc-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty/PlayStation-5-Slim-Blu-ray-Disc-Edition-1.jpg',
    image1: '/images/playstation/PlayStation-5-Slim-Blu-ray-Disc-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty/PlayStation-5-Slim-Blu-ray-Disc-Edition-2.jpg',
    image2: '/images/playstation/PlayStation-5-Slim-Blu-ray-Disc-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty/PlayStation-5-Slim-Blu-ray-Disc-Edition-3.jpg',
    image3: '/images/playstation/PlayStation-5-Slim-Blu-ray-Disc-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty/PlayStation-5-Slim-Blu-ray-Disc-Edition-4.jpg',
    category: 'playstation',
    stock: 30,
    features: ['Slim Design - With PS5 Disc Console, players get powerful gaming technology packed inside a sleek and compact console design.', '1TB of Storage - Keep your favorite games ready and waiting for you to jump in and play with 1TB of SSD storage built in.', 'Box Contents - 1 DualSense Wireless Controller, 2 Horizontal Stand Feet, HDMI Cable, AC Power Cord, USB cable, printed materials,', 'PS5 console CFI 2016 ']
  },
  {
    id: 'PlayStation-PS-VR2-plus-Horizon-Call-Of-Mountain-Voucher-Bundle-KSA-version',
    name: 'PlayStation PS VR2+Horizon Call Of Mountain Voucher Bundle - KSA version',
    price: 800.99,
    originalPrice: 932.99,
    description: 'Interact with virtual worlds in amazing new ways with haptic feedback1, adaptive triggers1, precision tracking and finger touch detection1 - all integrated into a unique ergonomic design. Conquer colossal peaks, overcome fearsome machines and uncover a hidden danger to the world of Horizon in the PlayStation VR2 Horizon Call of the Mountain bundle.',
    discount: 17,
    image: '/images/playstation/PlayStation-PS-VR2plusHorizon-Call-Of-Mountain-Voucher-Bundle-KSA-version/PlayStation-PS-VR2plusHorizon-Call-1.jpg',
    image1: '/images/playstation/PlayStation-PS-VR2plusHorizon-Call-Of-Mountain-Voucher-Bundle-KSA-version/PlayStation-PS-VR2plusHorizon-Call-2.jpg',
    image2: '/images/playstation/PlayStation-PS-VR2plusHorizon-Call-Of-Mountain-Voucher-Bundle-KSA-version/PlayStation-PS-VR2plusHorizon-Call-3.jpg',
    image3: '/images/playstation/PlayStation-PS-VR2plusHorizon-Call-Of-Mountain-Voucher-Bundle-KSA-version/PlayStation-PS-VR2plusHorizon-Call-4.jpg',
    category: 'playstation',
    stock: 25,
    features: ['Innovative PlayStation VR2 Sense technology brings emotion and immersion to life through subtle headset vibrations', '3D audio technology and intelligent eye tracking, combined with finger touch detection, haptic feedback and adaptive triggers from the PS VR2 Sense controller1. ', 'Two 2000x2040 OLED displays deliver incredible 4K HDR visuals at up to 120fps1, for 4x the resolution of the original PlayStationVR', 'PlayStationStore voucher code for Horizon Call of the Mountain*']
  },
  {
    id: 'PlayStation-5-Console-Marvel-Spider-Man-2-Limited-Edition-Bundle',
    name: 'PlayStation®5 Console Marvels Spider-Man 2 Limited Edition Bundle',
    price: 711.99,
    originalPrice: 852.99,
    description: 'PlayStation®5 Console  Marvels Spider-Man 2 Limited Edition Bundle Get the PlayStation 5 Console  Marvels Spider-Man 2 Limited Edition Bundle with a symbiote takeover design, and experience the next game in the Marvels Spider-Man franchise. This bundle includes a PS5 console with Limited Edition console covers, a Limited Edition DualSense wireless controller, a voucher for a digital copy of the game, and pre-order incentive items.*',
    discount: 17,
    image: '/images/playstation/PlayStation-5-Console-Marvel-Spider-Man-2-Limited-Edition-Bundle/PlayStation-5-Console-Marvel-1.jpg',
    image1: '/images/playstation/PlayStation-5-Console-Marvel-Spider-Man-2-Limited-Edition-Bundle/PlayStation-5-Console-Marvel-2.jpg',
    image2: '/images/playstation/PlayStation-5-Console-Marvel-Spider-Man-2-Limited-Edition-Bundle/PlayStation-5-Console-Marvel-3.jpg',
    image3: '/images/playstation/PlayStation-5-Console-Marvel-Spider-Man-2-Limited-Edition-Bundle/PlayStation-5-Console-Marvel-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ['This bundle includes a PS5 console with Limited Edition console covers, a Limited Edition DualSense wireless controller ', 'The DualSense wireless controller offers immersive haptic feedback*, dynamic adaptive triggers* and a built-in microphone, all integrated into an iconic comfortable design.', 'he only console covers made by PlayStation for PS5 that deliver the quality level you deserve. Easy to Use: Simply remove your original white PS5 console covers and click your new covers into place. ', 'Spider-Men, Peter Parker and Miles Morales, return for an exciting new adventure in the critically acclaimed Marvel’s Spider-Man franchise for PS5. ']
  },
  {
    id: 'PlayStation-Sony-5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-2023-KSA-Version-Brand-Sony-Interactive-Entertainment',
    name: 'PlayStation Sony 5 Slim Disc Edition DualSense Wireless Controller Double Pack (2023) - KSA Version Brand: Sony Interactive Entertainment',
    price: 560.99,
    originalPrice: 678.99,
    description: 'Contents Introduction: PS5 and 2 controllers will expand your gaming experience. This is a great value set that includes the controller included with the PS5 Disc Edition, plus another controller. The included PlayStation 5 is a new PS5 model group - slim, which is designed to be a smaller model with technologies and functions that provide a gaming experience. The internal SSD storage of the unit is 1TB Blu-Ray / Disc Version',
    discount: 20,
    image: '/images/playstation/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023)/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023).jpg',
    image1: '/images/playstation/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023)/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023).jpg',
    image2: '/images/playstation/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023)/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023).jpg',
    image3: '/images/playstation/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023)/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023).jpg',
    category: 'playstation',
    stock: 45,
    features: ['2 DualSense Wireless Controller', '2 Horizontal Stand Feet', 'HDMI Cable', 'AC Power Cord','USB cable, printed materials, ']
  },
  {
    id: 'PlayStation-5-Pro-Digital-Edition-Console-KSA-version-2-Year-Manufacturer-Warranty',
    name: 'PlayStation 5 Pro Digital Edition Console (KSA version), 2 Year Manufacturer Warranty',
    price: 700.99,
    originalPrice: 852.99,
    description: 'Witness Play Unleashed™ With the PlayStation®5 Pro console, the world’s greatest game creators can enhance their games with incredible features like advanced ray tracing, super sharp image clarity for your 4K TV, and high frame rate gameplay.',
    discount: 17,
    image: '/images/playstation/PlayStation-5-Pr-Digital-Edition-Console-(KSA-version)-2-Year-Manufacturer-Warranty/PlayStation-5-Pro-Digital-Edition-Console-1.jpg',
    image1: '/images/playstation/PlayStation-5-Pr-Digital-Edition-Console-(KSA-version)-2-Year-Manufacturer-Warranty/PlayStation-5-Pro-Digital-Edition-Console-2.jpg',
    image2: '/images/playstation/PlayStation-5-Pr-Digital-Edition-Console-(KSA-version)-2-Year-Manufacturer-Warranty/PlayStation-5-Pro-Digital-Edition-Console-3.jpg',
    image3: '/images/playstation/PlayStation-5-Pr-Digital-Edition-Console-(KSA-version)-2-Year-Manufacturer-Warranty/PlayStation-5-Pro-Digital-Edition-Console-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ['PlayStation Spectral Super Resolution (PSSR) - Get super sharp image clarity on your 4K TV using AI enhanced resolution for ultra-high definition play with astonishing detail ', 'Optimized Console Performance - Reach higher and more consistent frame rates for silky smooth gameplay with support for 60Hz and 120Hz displays. ', 'Advanced Ray Tracing - Experience next level realism with ray traced reflections, shadows, and high-quality global illumination as you explore stunning game worlds ']
  },
  {
    id: 'Sony-PlayStation-5-Pro-PS5-avec-1-Manette-Sans-Fil-DualSense-Couleur-Blanche',
    name: 'Sony, PlayStation 5 Pro, PS5 avec 1 Manette Sans Fil DualSense, Couleur : Blanche',
    price: 700.99,
    originalPrice: 890.99,
    description: 'With the PlayStation 5 Pro console, the worlds greatest game creators can enhance their games with incredible features like advanced ray tracing, crystal-clear 4K TV viewing, and high refresh rates. With PS5 games, you will experience the most impressive graphics ever seen on a PlayStation console. The PS5 Pro is a digital-only console and does not have a disc drive. Sign in to your PlayStationNetwork account, then visit the PlayStationStore to buy and download games. You can also add a disc drive to your PS5 Pro console if you want to play PS5 or PS4 games on Blu-ray Disc, or if you want to watch a movie or TV show on 4K Ultra HD Blu-ray Disc, Blu-ray Disc, or DVD. Features only available to PS5 games that have been Enhanced for PS5 Pro compared to PS5 games. Enhanced for PS5 Pro benefits are specific to each game.',
    discount: 17,
    image: '/images/playstation/Sony-PlayStation-5-Pro,PS5-avec-1-Manette-Sans-Fil-DualSense,Couleur:Blanche/Sony-PlayStation-5-Pro-1.jpg',
    image1: '/images/playstation/Sony-PlayStation-5-Pro,PS5-avec-1-Manette-Sans-Fil-DualSense,Couleur:Blanche/Sony-PlayStation-5-Pro-2.jpg',
    image2: '/images/playstation/Sony-PlayStation-5-Pro,PS5-avec-1-Manette-Sans-Fil-DualSense,Couleur:Blanche/Sony-PlayStation-5-Pro-3.jpg',
    image3: '/images/playstation/Sony-PlayStation-5-Pro,PS5-avec-1-Manette-Sans-Fil-DualSense,Couleur:Blanche/Sony-PlayStation-5-Pro-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ['Featuring an enhanced GPU, advanced ray tracing, and PlayStation Spectral Super Resolution, it takes gamers to new heights.', 'Enjoy ultra-sharp picture quality on your 4K TV with AI-enhanced resolution.', 'Console Optimized: With higher and more stable refresh rates, enjoy ultra-smooth gameplay supporting both 60Hz and 120Hz displays.']
  },
  {
    id: 'PlayStation-5-Digital-Edition-Slim-Nordic',
    name: 'PlayStation 5 Digital Edition Slim (Nordic)',
    price: 611.99,
    originalPrice: 777.74,
    description: 'PlayStation 5 Digital Edition Slim (Nordic)',
    discount: 17,
    image: '/images/playstation/PlayStation-5-Digital-Edition-Slim-(Nordic)/PlayStation-5-Digital-Edition-Slim-1.jpg',
    image1: '/images/playstation/PlayStation-5-Digital-Edition-Slim-(Nordic)/PlayStation-5-Digital-Edition-Slim-2.jpg',
    image2: '/images/playstation/PlayStation-5-Digital-Edition-Slim-(Nordic)/PlayStation-5-Digital-Edition-Slim-3.jpg',
    image3: '/images/playstation/PlayStation-5-Digital-Edition-Slim-(Nordic)/PlayStation-5-Digital-Edition-Slim-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ['Featuring an enhanced GPU, advanced ray tracing, and PlayStation Spectral Super Resolution, it takes gamers to new heights.', 'Enjoy ultra-sharp picture quality on your 4K TV with AI-enhanced resolution.', 'Console Optimized: With higher and more stable refresh rates, enjoy ultra-smooth gameplay supporting both 60Hz and 120Hz displays.']
  },
  {
    id: 'PlayStation-5-With-Blu-Ray-Disc-Console-SLIM-KSA-VERSION-FC25-and-Two-White-Controllers-Bundle',
    name: 'PlayStation 5 With Blu-Ray Disc Console (SLIM) KSA VERSION + FC25 and Two White Controllers Bundle',
    price: 600.99,
    originalPrice: 746.99,
    description: 'Slim Design - With PS5 Disc Console, players get powerful gaming technology packed inside a sleek and compact console design. Including Extra controller and FC 25',
    discount: 17,
    image: '/images/playstation/PlayStation-5-With-Blu-Ray-Disc-Console-(SLIM)-KSA-VERSION-FC25-and-Two-White-Controllers-Bundle/PlayStation-5-With-Blu-Ray-Disc-Console-1.jpg',
    image1: '/images/playstation/PlayStation-5-With-Blu-Ray-Disc-Console-(SLIM)-KSA-VERSION-FC25-and-Two-White-Controllers-Bundle/PlayStation-5-With-Blu-Ray-Disc-Console-2.jpg',
    image2: '/images/playstation/PlayStation-5-With-Blu-Ray-Disc-Console-(SLIM)-KSA-VERSION-FC25-and-Two-White-Controllers-Bundle/PlayStation-5-With-Blu-Ray-Disc-Console-3.jpg',
    image3: '/images/playstation/PlayStation-5-With-Blu-Ray-Disc-Console-(SLIM)-KSA-VERSION-FC25-and-Two-White-Controllers-Bundle/PlayStation-5-With-Blu-Ray-Disc-Console-1.jpg',
    category: 'playstation',
    stock: 20,
    features: ['Disc Edition', 'Spectral Super Resolution', 'DualSense controller', 'Digital content']
  },
  {
    id: 'SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version',
    name: 'SIE Sony PlayStation 5 Slim Disc with Extra Dualsense Black Controller - International Version',
    price: 533.99,
    originalPrice: 666.29,
    description: 'The PS5 model (model group - slim) is a new model that achieves a smaller size with technologies and functions that deliver the experience of the PlayStation 5. The Ultra HD Blu-ray disc drive is detachable and the internal SSD storage in the unit becomes 1TB.',
    discount: 17,
    image: '/images/playstation/SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version/SIE-Sony-PlayStation-5-Slim-Disc-1.jpg',
    image1: '/images/playstation/SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version/SIE-Sony-PlayStation-5-Slim-Disc-2.jpg',
    image2: '/images/playstation/SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version/SIE-Sony-PlayStation-5-Slim-Disc-3.jpg',
    image3: '/images/playstation/SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version/SIE-Sony-PlayStation-5-Slim-Disc-1.jpg',
    category: 'playstation',
    stock: 20,
    features: ['PS5 Slim Disc and 2 controllers will expand your gaming experience. This is a great value set that includes a controller that comes with a PS5 unit as well as an additional Black dualsense controller', 'The PS5 Slim model (model group - slim) is a new model that achieves a smaller size with technologies and functions that deliver the experience of the PlayStation 5. The Ultra HD Blu-ray disc drive is detachable and the internal SSD storage in the unit becomes 1TB ', 'PlayStation 5 Description: Play Has No Limits for new game possibilities with unleash PS5 that exceeds the limits of play. Super fast SSD dramatically improves read speed Haptic technology, adaptive trigger, and 3D audio technology deliver a dense immersive feel. And experience the new generation of amazing PlayStation titles ', 'Digital content']
  },
  {
    id: 'Sony-PlayStation-5-Console',
    name: 'Sony PlayStation 5 Console',
    price: 900.99,
    originalPrice: 1066.23,
    description: 'The PS5™ console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation® games.',
    discount: 17,
    image: '/images/playstation/Sony-PlayStation-5-Console/Sony-PlayStation-5-Console-1.jpg',
    image1: '/images/playstation/Sony-PlayStation-5-Console/Sony-PlayStation-5-Console-2.jpg',
    image2: '/images/playstation/Sony-PlayStation-5-Console/Sony-PlayStation-5-Console-3.jpg',
    image3: '/images/playstation/Sony-PlayStation-5-Console/Sony-PlayStation-5-Console-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ['The PS5 console unleashes new gaming possibilities that you never anticipated.', 'Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation games.', 'Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation console can do. ', 'Marvel at incredible graphics and experience new PS5 features. ']
  },
  {
    id: 'Sony-85-Inch-4K-Mini-LED-HDR-BRAVIA-XR-UHD-Smart-Google-TV-HDMI-2-1-For-The-Playstation-5-XR85X95L-2-Years-Warranty2023Model-KSA-Version',
    name: 'Sony 85 Inch 4K Mini LED HDR BRAVIA XR UHD Smart Google TV HDMI 2.1 For The Playstation 5 XR85X95L 2 Years Warranty (2023 Model - KSA Version)',
    price: 4159.99,
    originalPrice: 5159.98,
    description: 'Sony BRAVIA XR 85 Inch Mini LED TV 4K UHD HDR Smart Google TV HDMI 2.1 For The Playstation 5 - XR-85X95L (2023 Model)',
    discount: 17,
    image: '/images/playstation/Sony-85-Inch-4K-Mini-LED-HDR-BRAVIA-XR-UHD-Smart-Google-TV-HDMI-2.1-For-The-Playstation-5-XR85X95L-2-Years-Warranty2023Model-KSA-Version/Sony-85-Inch-4K-Mini-LED-HDR-BRAVIA-XR-UHD-1.jpg',
    image1: '/images/playstation/Sony-85-Inch-4K-Mini-LED-HDR-BRAVIA-XR-UHD-Smart-Google-TV-HDMI-2.1-For-The-Playstation-5-XR85X95L-2-Years-Warranty2023Model-KSA-Version/Sony-85-Inch-4K-Mini-LED-HDR-BRAVIA-XR-UHD-2.jpg',
    image2: '/images/playstation/Sony-85-Inch-4K-Mini-LED-HDR-BRAVIA-XR-UHD-Smart-Google-TV-HDMI-2.1-For-The-Playstation-5-XR85X95L-2-Years-Warranty2023Model-KSA-Version/Sony-85-Inch-4K-Mini-LED-HDR-BRAVIA-XR-UHD-3.jpg',
    image3: '/images/playstation/Sony-85-Inch-4K-Mini-LED-HDR-BRAVIA-XR-UHD-Smart-Google-TV-HDMI-2.1-For-The-Playstation-5-XR85X95L-2-Years-Warranty2023Model-KSA-Version/Sony-85-Inch-4K-Mini-LED-HDR-BRAVIA-XR-UHD-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ['SCENES WITH MORE SPARKLE: Our Cognitive Processor XR brings out the brilliance and depth of contrast in each scene ', 'PRECISELY CONTROLLED: A 4K Mini LED screen is precisely controlled by our powerful XR Backlight Master Drive', 'OVER A BILLION COLORS: Extended color volume, now see every shade and hue ', 'AUDIO MATCHES THE ACTION: Tweeters in the TV frame mean that audio fits perfectly with the on screen action','LEVEL UP YOUR GAMING: Discover a whole new gaming experience with Game Menu']
  },
  {
    id: 'PlayStation-VR-Mega-Pack-PS4',
    name: 'PlayStation VR Mega Pack (PS4/)',
    price: 803.99,
    originalPrice: 903.59,
    description: 'Live the game with PS VR - The new great-value PlayStation VR Mega Pack takes you straight to the heart of five thrilling VR adventures. Immerse yourself in hundreds of mind-blowing virtual reality games and experiences. Travel through an endless universe, explore fantasy realms, blast your way through the criminal underworld, and lose yourself to the beat. Play supported PS VR games on PlayStation 5 playing PS VR games on a PS5 console requires a PS VR headset, PlayStation Camera for PS4 and a PlayStation Camera adaptor (all included in the bundle). for the best PS VR experience on PS5 we recommend using a dualshock 4 wireless controller. Selected games may require PlayStation Move motion controllers or be compatible with the PlayStation VR aim controller. The new HD camera for PS5 is not compatible with PS VR. The PS VR headset, PS camera, dualshock 4 wireless controller, PS Move controllers and PS VR aim controller are all sold separately from PS5. Astro Bot rescue mission and Moss require dualshock 4 wireless controller (DS4). everybodys golf VR, Blood & truth and the London heist (PlayStation VR Worlds) require PS Move controllers or DS4, sold separately',
    discount: 17,
    image: '/images/playstation/PlayStation-VR-Mega-Pack-PS4/PlayStation-VR-Mega-Pack-1.jpg',
    image1: '/images/playstation/PlayStation-VR-Mega-Pack-PS4/PlayStation-VR-Mega-Pack-2.jpg',
    image2: '/images/playstation/PlayStation-VR-Mega-Pack-PS4/PlayStation-VR-Mega-Pack-3.jpg',
    image3: '/images/playstation/PlayStation-VR-Mega-Pack-PS4/PlayStation-VR-Mega-Pack-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ["Includes five acclaimed games to download from PlayStation store - ASTRO Bot rescue mission, Everybody's golf VR, Moss, Blood and truth and PlayStation VR Worlds. Note: Customer Support number 0203 538 2665 ", "360 vision - absorb every second of the action through a custom 5.7' Oled screen with smooth visuals and Super low latency 3D audio - hear approaching footsteps or distant screams with pinpoint accuracy through cutting-edge Surround Sound ", "intuitive controls - A complete tracking system follows every movement of the dualshock 4 Wireless Controller, PlayStation Move motion controllers) or PlayStation VR aim controller ", "built-in microphone - chat with friends to swap hints and tactics with the built-in microphone"]
  },
  {
    id: 'PlayStation VR Marvels Iron Man VR (PS4)',
    name: 'PlayStation VR Marvels Iron Man VR (PS4)',
    price: 499.99,
    originalPrice: 599.99,
    description: "Bundle includes PlayStationVR headset, PlayStationCamera, 2 PlayStation Move motion controllers, Marvel's Iron Man VR Blue-Ray Disc, and Demo Disc 3.0. Using two PlayStation Move motion controllers** fire up Iron Man's Repulsor Jets and blast into the skies with an arsenal of iconic Iron Man gear at your fingertips. Face off against one of Iron Man's greatest foes in high stakes, action-packed battles. Upgrade tech in Tony Stark's garage to customize Iron Man's sleek armor and awesome abilities.",
    discount: 17,
    image: '/images/playstation/PlayStation-VR-Marvels-Iron-Man-VR-PS4/PlayStation-VR-Marvel-Iron-Man-1.jpg',
    image1: '/images/playstation/PlayStation-VR-Marvels-Iron-Man-VR-PS4/PlayStation-VR-Marvel-Iron-Man-2.jpg',
    image2: '/images/playstation/PlayStation-VR-Marvels-Iron-Man-VR-PS4/PlayStation-VR-Marvel-Iron-Man-3.jpg',
    image3: '/images/playstation/PlayStation-VR-Marvels-Iron-Man-VR-PS4/PlayStation-VR-Marvel-Iron-Man-4.jpg',
    category: 'playstation',
    stock: 20,
    features: [" Marvel's Iron Man VR Blue-Ray Disc, and Demo Disc 3.0 2 PlayStation Move motion controllers PlayStationVR headset PlayStationCamera ", "Using two PlayStation Move motion controllers** fire up Iron Man's Repulsor Jets and blast into the skies with an arsenal of iconic Iron Man gear at your fingertips. Face off against one of Iron Man's greatest foes in high stakes, action-packed battles. Upgrade tech in Tony Stark's garage tocustomize Iron Man's sleek armorand awesome abilities"]
  },

  // MacBook Category
  {
    id: 'macbook-pro-16',
    name: 'MacBook Pro 16"',
    price: 2299.99,
    originalPrice: 2499.99,
    description: 'Ultimate power for ultimate professionals',
    discount: 8,
    image: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image1: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image2: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image3: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    category: 'macbook',
    stock: 35,
    features: ['M3 Max chip', '32GB RAM', '1TB SSD', '16" Liquid Retina XDR']
  },
  {
    id: 'macbook-pro-14',
    name: 'MacBook Pro 14"',
    price: 1799.99,
    originalPrice: 1999.99,
    description: 'Pro performance in a portable size',
    discount: 10,
    image: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image1: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image2: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image3: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    category: 'macbook',
    stock: 40,
    features: ['M3 Pro chip', '16GB RAM', '512GB SSD', '14" Liquid Retina XDR']
  },
  {
    id: 'macbook-air-15',
    name: 'MacBook Air 15"',
    price: 1299.99,
    originalPrice: 1499.99,
    description: 'Incredibly thin. Seriously powerful.',
    discount: 13,
    image: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image1: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image2: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image3: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    category: 'macbook',
    stock: 60,
    features: ['M3 chip', '16GB RAM', '512GB SSD', '15" Liquid Retina']
  },
  {
    id: 'macbook-air-13',
    name: 'MacBook Air 13"',
    price: 999.99,
    originalPrice: 1199.99,
    description: 'The most affordable MacBook Air',
    discount: 17,
    image: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image1: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image2: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image3: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    category: 'macbook',
    stock: 85,
    features: ['M3 chip', '8GB RAM', '256GB SSD', '13.6" Liquid Retina']
  },
  {
    id: 'Apple-MacBook-Air-13.3wTouch-ID-Fall-2020-Silver-Apple-M1-Chip-256GB-SSD-8GB-RAM-En-Open-Box',
    name: 'Apple MacBook Air 13.3" w/ Touch ID (Fall 2020) - Silver (Apple M1 Chip / 256GB SSD / 8GB RAM) - En - Open Box',
    price: 747.99,
    originalPrice: 847.99,
    description: 'Minimum 1-year warranty. See more information below.** Apples thinnest and lightest notebook gets supercharged with the Apple M1 chip. Tackle your projects with the blazing-fast 8-core CPU. Take graphics-intensive apps and games to the next level with a 7-core GPU. Accelerate machine-learning tasks with the 16-core Neural Engine. All with a silent and fanless design.',
    discount: 8,
    image: '/images/macbook/Apple-MacBook-Air-13.3-1/Apple-MacBook-Air-13.3-1-1.jpeg',
    image1: '/images/macbook/Apple-MacBook-Air-13.3-1/Apple-MacBook-Air-13.3-1-2.jpeg',
    image2: '/images/macbook/Apple-MacBook-Air-13.3-1/Apple-MacBook-Air-13.3-1-3.jpeg',
    image3: '/images/macbook/Apple-MacBook-Air-13.3-1/Apple-MacBook-Air-13.3-1-4.jpeg',
    category: 'macbook',
    stock: 35,
    features: ['Apple-designed M1 chip for a giant leap in CPU, GPU, and machine-learning performance', '8-core CPU delivers up to 3.5 times faster performance to tackle projects faster than ever', '16-core Neural Engine for advanced machine learning', '8GB of unified memory so everything you do is fast and fluid ','256GB of super-fast SSD storage launches apps and opens files in an instant','7-core GPU with up to 5 times faster graphics for graphics-intensive apps and games','13.3-inch Retina display with P3 wide colour for vibrant images and incredible detail','Next-generation Wi-Fi 6 for faster connectivity']
  },
  {
    id: 'Apple-13.3"-MacBook-Air-with-Retina-Display-(Late 2020)',
    name: 'Apple 13.3" MacBook Air with Retina Display (Late 2020)',
    price: 894.95,
    originalPrice: 994.95,
    description: 'Apple MacBook Air with Apple M1 Chip (13-inch, 8GB RAM, 256GB)',
    discount: 8,
    image: '/images/macbook/Apple-MacBook-Air-13.3-2/Apple-MacBook-Air-13.3-2-1.jpeg',
    image1: '/images/macbook/Apple-MacBook-Air-13.3-2/Apple-MacBook-Air-13.3-2-2.jpeg',
    image2: '/images/macbook/Apple-MacBook-Air-13.3-2/Apple-MacBook-Air-13.3-2-3.jpeg',
    image3: '/images/macbook/Apple-MacBook-Air-13.3-2/Apple-MacBook-Air-13.3-2-4.jpeg',
    category: 'macbook',
    stock: 35,
    features: ['Brand New', 'Screen Size 13.3 in', 'Colour Silver', 'Dimensions (cm) 10.000 (W) x ']
  },
  {
    id: 'Apple-MacBook-Air-13.6"w/Touch-ID(2025)-Sky-Blue(AppleM4/16GBRAM/256GBSSD)-English',
    name: 'Apple MacBook Air 13.6" w/ Touch ID (2025) - Sky Blue (Apple M4 / 16GB RAM / 256GB SSD) - English',
    price: 999.99,
    originalPrice: 1199.99,
    description: 'The 13-inch MacBook Air with the M4 chip lets you fly through work and play. With Apple Intelligence,1 a brilliant Liquid Retina display,2 and a strikingly thin and light design, it’s built to last and can take on just about anything, anywhere.',
    discount: 8,
    image: '/images/macbook/Apple-MacBook-Air-13.3-3/Apple-MacBook-Air-13.3-3-1.jpeg',
    image1: '/images/macbook/Apple-MacBook-Air-13.3-3/Apple-MacBook-Air-13.3-3-1.jpeg',
    image2: '/images/macbook/Apple-MacBook-Air-13.3-3/Apple-MacBook-Air-13.3-3-1.jpeg',
    image3: '/images/macbook/Apple-MacBook-Air-13.3-3/Apple-MacBook-Air-13.3-3-1.jpeg',
    category: 'macbook',
    stock: 35,
    features: ['Touch ID (2025)', 'Apple M4', '16GB RAM', '256GB']
  },
  {
    id: 'Apple MacBook Air 13.6" w/ Touch ID (2022) - Starlight (Apple M2 / 16GB RAM / 256GB SSD)-English',
    name: 'Apple MacBook Air 13.6" w/ Touch ID (2022) - Starlight (Apple M2 / 16GB RAM / 256GB SSD) - English',
    price: 899.99,
    originalPrice: 999.99,
    description: 'The Apple MacBook Air is supercharged with the Apple M2 chip. You can work with more streams of 4K and 8K ProRes video with the high‑performance media engine, and keep working — or playing.',
    discount: 8,
    image: '/images/macbook/Apple-MacBook-Air-13.3-4/Apple-MacBook-Air-13.3-4-1.jpeg',
    image1: '/images/macbook/Apple-MacBook-Air-13.3-4/Apple-MacBook-Air-13.3-4-1.jpeg',
    image2: '/images/macbook/Apple-MacBook-Air-13.3-4/Apple-MacBook-Air-13.3-4-1.jpeg',
    image3: '/images/macbook/Apple-MacBook-Air-13.3-4/Apple-MacBook-Air-13.3-4-1.jpeg',
    category: 'macbook',
    stock: 35,
    features: ['Apple M2', '16GB RAM', '1TB SSD', '256GB SSD']
  },
  {
    id: 'Apple MacBook Air 13.6" w/ Touch ID (2025) - Starlight (Apple M4 / 16GB RAM / 256GB SSD) - English',
    name: 'Apple MacBook Air 13.6" w/ Touch ID (2025) - Starlight (Apple M4 / 16GB RAM / 256GB SSD) - English',
    price: 1004.99,
    originalPrice: 1244.99,
    description: 'The 13-inch MacBook Air with the M4 chip lets you fly through work and play. With Apple Intelligence, a brilliant Liquid Retina display, and a strikingly thin and light design, it’s built to last and can take on just about anything, anywhere.',
    discount: 8,
    image: '/images/macbook/Apple-MacBook-Air-13.3-5/Apple-MacBook-Air-13.3-5-1.jpeg',
    image1: '/images/macbook/Apple-MacBook-Air-13.3-5/Apple-MacBook-Air-13.3-5-1.jpeg',
    image2: '/images/macbook/Apple-MacBook-Air-13.3-5/Apple-MacBook-Air-13.3-5-1.jpeg',
    image3: '/images/macbook/Apple-MacBook-Air-13.3-5/Apple-MacBook-Air-13.3-5-1.jpeg',
    category: 'macbook',
    stock: 35,
    features: ['Year of Original Release 2025', 'Apple M4 Chip', '4th Generation', '256GB SSD']
  },
  {
    id: 'Apple-MacBook-Air-13.6"w/Touch-ID(2025)-Midnight(Apple-M4/16GBRAM/512GBSSD)-English',
    name: 'Apple MacBook Air 13.6" w/ Touch ID (2025) - Midnight (Apple M4 / 16GB RAM / 512GB SSD) - English',
    price: 1234.99,
    originalPrice: 1434.99,
    description: 'The 13-inch MacBook Air with the M4 chip lets you fly through work and play. With Apple Intelligence, a brilliant Liquid Retina display, and a strikingly thin and light design, it’s built to last and can take on just about anything, anywhere.',
    discount: 8,
    image: '/images/macbook/Apple-MacBook-Air-13.3-5/Apple-MacBook-Air-13.3-5-1.jpeg',
    image1: '/images/macbook/Apple-MacBook-Air-13.3-5/Apple-MacBook-Air-13.3-5-1.jpeg',
    image2: '/images/macbook/Apple-MacBook-Air-13.3-5/Apple-MacBook-Air-13.3-5-1.jpeg',
    image3: '/images/macbook/Apple-MacBook-Air-13.3-5/Apple-MacBook-Air-13.3-5-1.jpeg',
    category: 'macbook',
    stock: 35,
    features: ['Year of Original Release 2025', 'Apple M4 Chip', '4th Generation', '512GB SSD']
  },
];
