interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice: number;
  description: string;
  discount: number;
  image: string;
  image1: string;
  image2: string;
  image3: string;
  category: 'iphone' | 'playstation' | 'macbook';
  stock: number;
  features: string[];
}

export const products: Product[] = [
  // iPhone Category
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    price: 1099.99,
    originalPrice: 1299.99,
    description: 'The most powerful iPhone ever with revolutionary A18 Pro chip',
    discount: 15,
    image: '/images/iphones/iphone_16_pro_max/iphone_16_pro_max_1.jpg',
    image1: '/images/iphones/iphone_16_pro_max/iphone_16_pro_max_2.jpg',
    image2: '/images/iphones/iphone_16_pro_max/iphone_16_pro_max_3.jpg',
    image3: '/images/iphones/iphone_16_pro_max/iphone_16_pro_max_4.jpg',
    category: 'iphone',
    stock: 50,
    features: ['6.9" Super Retina XDR display', 'A18 Pro chip', '1TB storage', 'Titanium design']
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    price: 999.99,
    originalPrice: 1199.99,
    description: 'Pro camera system for mind-blowing shots',
    discount: 17,
    image: '/images/iphones/iphone-16-pro/iphone-16-pro-1.webp',
    image1: '/images/iphones/iphone-16-pro/iphone-16-pro-2.webp',
    image2: '/images/iphones/iphone-16-pro/iphone-16-pro-3.webp',
    image3: '/images/iphones/iphone-16-pro/iphone-16-pro-4.webp',
    category: 'iphone',
    stock: 75,
    features: ['6.7" Super Retina XDR display', 'A18 Pro chip', '512GB storage', 'Pro camera system']
  },
  {
    id: 'iphone-16-plus',
    name: 'iPhone 16 Plus',
    price: 899.99,
    originalPrice: 999.99,
    description: 'Big beautiful display with all-day battery life',
    discount: 10,
    image: '/images/iphones/iphone-16-plus/apple-iphone-16-plus-1.jpg',
    image1: '/images/iphones/iphone-16-plus/apple-iphone-16-plus-2.jpg',
    image2: '/images/iphones/iphone-16-plus/apple-iphone-16-plus-3.jpg',
    image3: '/images/iphones/iphone-16-plus/apple-iphone-16-plus-4.jpg',
    category: 'iphone',
    stock: 100,
    features: ['6.7" Super Retina display', 'A18 chip', '256GB storage', 'Dual camera']
  },
  {
    id: 'iphone-16',
    name: 'iPhone 16',
    price: 799.99,
    originalPrice: 899.99,
    description: 'The perfect iPhone for everyone',
    discount: 11,
    image: '/images/iphones/iphone-16/iphone-16-1.jpg',
    image1: '/images/iphones/iphone-16/iphone-16-2.jpg',
    image2: '/images/iphones/iphone-16/iphone-16-3.jpg',
    image3: '/images/iphones/iphone-16/iphone-16-4.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.1" Super Retina display', 'A18 chip', '128GB storage', 'All-day battery']
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    price: 350.99,
    originalPrice: 450.99,
    description: 'Unlocked for freedom to choose your carrier. Compatible with both GSM & CDMA networks. The phone is unlocked to work with all GSM Carriers & CDMA Carriers Including AT&T, T-Mobile, Verizon, Sprint., Etc',
    discount: 11,
    image: '/images/iphones/iphone-15/iphone-15-1.webp',
    image1: '/images/iphones/iphone-15/iphone-15-2.webp',
    image2: '/images/iphones/iphone-15/iphone-15-3.webp',
    image3: '/images/iphones/iphone-15/iphone-15-4.webp',
    category: 'iphone',
    stock: 150,
    features: ['6.1" Super Retina XDR OLED', 'HDR10', 'Dolby Vision', '1000 nits (HBM)','3349mAh Battery','128GB 6GB']
  },
  {
    id: 'iphone-15-plus',
    name: 'iPhone 15 plus',
    price: 700.99,
    originalPrice: 852.99,
    description: 'iPhone 15 plus features a durable colour-infused glass and aluminium design. It’s splash, water and dust resistant.1 The Ceramic Shield front is super-tough. And the 6.7” Super Retina XDR display2 is up to 2x brighter in the sun compared to iPhone 14',
    discount: 11,
    image: '/images/iphones/iphone-15-plus/iPhone_15_Plus_Green_PDP_Image_Position-1_alt__en-IN.jpg',
    image1: '/images/iphones/iphone-15-plus/iPhone_15_Plus_Green_PDP_Image_Position-1__en-IN.jpg',
    image2: '/images/iphones/iphone-15-plus/iPhone_15_Plus_Green_PDP_Image_Position-2__en-IN.jpg',
    image3: '/images/iphones/iphone-15-plus/iPhone_15_Plus_Green_PDP_Image_Position-3__en-IN.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.7” Super Retina XDR display2', 'Ceramic Shield front', '48MP MAIN CAMERA WITH 2X TELEPHOTO', '1000 nits (HBM)','3349mAh Battery','128GB 6GB']
  },
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 pro',
    price: 900.99,
    originalPrice: 1013.29,
    description: 'The iPhone 15 Pro features an aerospace‑grade titanium design with an all‑new Action button to fast track to your favorite feature. The powerful camera system offers multiple focal lengths for super‑high‑resolution photos with a new level of detail and color.',
    discount: 11,
    image: '/images/iphones/iphone-15-pro/iPhone_15_Pro_Natural_Titanium_PDP_Image_Position-1_alt__en-IN.jpg',
    image1: '/images/iphones/iphone-15-pro/iPhone_15_Pro_Natural_Titanium_PDP_Image_Position-1__en-IN.jpg',
    image2: '/images/iphones/iphone-15-pro/iPhone_15_Pro_Natural_Titanium_PDP_Image_Position-2__en-IN.jpg',
    image3: '/images/iphones/iphone-15-pro/iPhone_15_Pro_Natural_Titanium_PDP_Image_Position-3__en-IN.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.1” Super Retina XDR display', 'ProMotion Technology', 'Megapowerful 48MP camera', ' 3x optical zoom and 15x digital zoom','Up to 23 hours video playback','Facetime is available']
  },
  {
    id: 'iphone-14',
    name: 'iPhone 14',
    price: 476.99,
    originalPrice: 586.99,
    description: 'iPhone 14 offers Vital safety features—Emergency SOS via satellite and Crash Detection with Industry-leading durability features with Ceramic Shield and water resistance',
    discount: 11,
    image: '/images/iphones/iphone-14/iPhone_14_Starlight_PDP_Image_Position-1B__WWEN_a6501dcd-195a-4f4f-b3b7-86244f02e5b8.jpg',
    image1: '/images/iphones/iphone-14/iPhone_14_Starlight_PDP_Image_Position-1A__WWEN_d53da00d-03ea-40db-8c13-08227bfb5e3a.jpg',
    image2: '/images/iphones/iphone-14/iPhone_14_Starlight_PDP_Image_Position-2__WWEN_1300817b-8ceb-4aef-9b84-d8d5fe5b64f8.jpg',
    image3: '/images/iphones/iphone-14/iPhone_14_Starlight_PDP_Image_Position-3__WWEN_49138210-1066-4514-87d3-6ebda6cd52f4.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.1-inch Super Retina XDR display', 'Advanced camera system for better photos in any light', 'Cinematic mode now in 4K Dolby Vision up to 30 fps ', ' Action mode for smooth, steady, handheld videos','Up to 23 hours video playback','Facetime is available']
  },
  {
    id: 'iphone-14-plus',
    name: 'iPhone 14 plus',
    price: 500.99,
    originalPrice: 639.99,
    description: 'Meet iPhone 14 Plus. With Crash Detection. Longer battery life than ever. And even more spectacular low-light shots. All in five great colors.',
    discount: 11,
    image: '/images/iphones/iphone-14-plus/iPhone_14_Plus_Blue_PDP_Image_Position-1B__WWEN_6c5b3bfe-9097-4144-a832-1508311a938d.jpg',
    image1: '/images/iphones/iphone-14-plus/iPhone_14_Plus_Blue_PDP_Image_Position-1A__WWEN_20fc3205-e675-4d4e-88d8-8cb06e5ccded.jpg',
    image2: '/images/iphones/iphone-14-plus/iPhone_14_Plus_Blue_PDP_Image_Position-2__WWEN_fb3157b2-5ae9-4468-8c4b-77b64a38048c.jpg',
    image3: '/images/iphones/iphone-14-plus/iPhone_14_Plus_Blue_PDP_Image_Position-3__WWEN_3c78aed1-f8c4-4b74-94db-e4f6c9721358.jpg',
    category: 'iphone',
    stock: 150,
    features: ['6.7-inch Super Retina XDR display ', 'Advanced camera system for better photos in any light', 'Cinematic mode now in 4K Dolby Vision up to 30 fps ', ' Action mode for smooth, steady, handheld videos','All-day battery life and up to 26 hours of video playback','A15 Bionic chip with 5-core GPU for lightning-fast performance. Superfast 5G cellular ']
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 pro',
    price: 610.99,
    originalPrice: 711.99,
    description: 'The iPhone 14 pro features a 6.1-inch Super Retina XDR display with ProMotion technology, an "Always-On" display, and a "Dynamic Island" that replaces the traditional notch. It also boasts a pro camera system with a 48MP main camera, 12MP ultra wide, and 12MP telephoto lenses. The iPhone 14 Pro is powered by the A16 Bionic chip and includes advanced safety features like Crash Detection',
    discount: 11,
    image: '/images/iphones/iphone-14-pro/iPhone_14_Blue_PDP_Image_Position-1A__WWEN.jpg',
    image1: '/images/iphones/iphone-14-pro/iPhone_14_Blue_PDP_Image_Position-1B__WWEN.jpg',
    image2: '/images/iphones/iphone-14-pro/iPhone_14_Blue_PDP_Image_Position-2__WWEN.jpg',
    image3: '/images/iphones/iphone-14-pro/iPhone_14_Blue_PDP_Image_Position-3__WWEN.jpg',
    category: 'iphone',
    stock: 150,
    features: ['Super Retina XDR OLED, 6.1 inches ', 'A16 Bionic chip', 'Triple 12MP system: Ultra Wide, Wide, Telephoto', ' 12MP TrueDepth Camera FrontCameraa','All-day battery life and up to 26 hours of video playback','A15 Bionic chip with 5-core GPU for lightning-fast performance. Superfast 5G cellular ']
  },

  // PlayStation 5 Category
  {
    id: 'ps5-digital',
    name: 'PS5 Digital Edition',
    price: 399.99,
    originalPrice: 499.99,
    description: 'Next-gen gaming without the disc drive',
    discount: 20,
    image: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image1: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image2: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image3: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    category: 'playstation',
    stock: 45,
    features: ['Digital Edition', '825GB SSD', '4K gaming', 'Ray tracing']
  },
  {
    id: 'ps5-disc',
    name: 'PS5 Disc Edition',
    price: 449.99,
    originalPrice: 549.99,
    description: 'The complete PS5 experience with disc drive',
    discount: 18,
    image: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image1: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image2: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image3: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    category: 'playstation',
    stock: 30,
    features: ['4K Blu-ray drive', '825GB SSD', '4K gaming', '3D Audio']
  },
  {
    id: 'ps5-horizon',
    name: 'PS5 Horizon Bundle',
    price: 499.99,
    originalPrice: 599.99,
    description: 'PS5 with Horizon Forbidden West game',
    discount: 17,
    image: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image1: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image2: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image3: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    category: 'playstation',
    stock: 25,
    features: ['Disc Edition', 'Horizon game', 'DualSense controller', 'Premium theme']
  },
  {
    id: 'ps5-spiderman',
    name: 'PS5 Spider-Man Bundle',
    price: 499.99,
    originalPrice: 599.99,
    description: 'PS5 with Spider-Man 2 game',
    discount: 17,
    image: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image1: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image2: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    image3: 'https://images.pexels.com/photos/12719149/pexels-photo-12719149.jpeg',
    category: 'playstation',
    stock: 20,
    features: ['Disc Edition', 'Spider-Man 2', 'DualSense controller', 'Digital content']
  },
  {
    id: 'PlayStation-Sony-5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023)-KSA Version Brand:-Sony-Interactive-Entertainment',
    name: 'PlayStation Sony 5 Slim Disc Edition DualSense Wireless Controller Double Pack (2023) - KSA Version Brand: Sony Interactive Entertainment',
    price: 560.99,
    originalPrice: 678.99,
    description: 'Contents Introduction: PS5 and 2 controllers will expand your gaming experience. This is a great value set that includes the controller included with the PS5 Disc Edition, plus another controller. The included PlayStation 5 is a new PS5 model group - slim, which is designed to be a smaller model with technologies and functions that provide a gaming experience. The internal SSD storage of the unit is 1TB Blu-Ray / Disc Version',
    discount: 20,
    image: '/images/playstation/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023)/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023).jpg',
    image1: '/images/playstation/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023)/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023).jpg',
    image2: '/images/playstation/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023)/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023).jpg',
    image3: '/images/playstation/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023)/PlayStation-Sony 5-Slim-Disc-Edition-DualSense-Wireless-Controller-Double-Pack-(2023).jpg',
    category: 'playstation',
    stock: 45,
    features: ['2 DualSense Wireless Controller', '2 Horizontal Stand Feet', 'HDMI Cable', 'AC Power Cord','USB cable, printed materials, ']
  },
  {
    id: 'PlayStation 5 Pro Digital Edition Console (KSA version), 2 Year Manufacturer Warranty',
    name: 'PlayStation-5-Pro-Digital-Edition-Console-(KSA-version),-2-Year-Manufacturer-Warranty',
    price: 700.99,
    originalPrice: 852.99,
    description: 'Witness Play Unleashed™ With the PlayStation®5 Pro console, the world’s greatest game creators can enhance their games with incredible features like advanced ray tracing, super sharp image clarity for your 4K TV, and high frame rate gameplay.',
    discount: 17,
    image: '/images/playstation/PlayStation-5-Pr-Digital-Edition-Console-(KSA-version)-2-Year-Manufacturer-Warranty/PlayStation-5-Pro-Digital-Edition-Console-1.jpg',
    image1: '/images/playstation/PlayStation-5-Pr-Digital-Edition-Console-(KSA-version)-2-Year-Manufacturer-Warranty/PlayStation-5-Pro-Digital-Edition-Console-2.jpg',
    image2: '/images/playstation/PlayStation-5-Pr-Digital-Edition-Console-(KSA-version)-2-Year-Manufacturer-Warranty/PlayStation-5-Pro-Digital-Edition-Console-3.jpg',
    image3: '/images/playstation/PlayStation-5-Pr-Digital-Edition-Console-(KSA-version)-2-Year-Manufacturer-Warranty/PlayStation-5-Pro-Digital-Edition-Console-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ['PlayStation Spectral Super Resolution (PSSR) - Get super sharp image clarity on your 4K TV using AI enhanced resolution for ultra-high definition play with astonishing detail ', 'Optimized Console Performance - Reach higher and more consistent frame rates for silky smooth gameplay with support for 60Hz and 120Hz displays. ', 'Advanced Ray Tracing - Experience next level realism with ray traced reflections, shadows, and high-quality global illumination as you explore stunning game worlds ']
  },
  {
    id: 'Sony, PlayStation 5 Pro, PS5 avec 1 Manette Sans Fil DualSense, Couleur : Blanche ',
    name: 'Sony,PlayStation-5-Pro,PS5-avec-1-Manette-Sans-Fil-DualSense,Couleur:Blanche ',
    price: 700.99,
    originalPrice: 890.99,
    description: 'With the PlayStation 5 Pro console, the worlds greatest game creators can enhance their games with incredible features like advanced ray tracing, crystal-clear 4K TV viewing, and high refresh rates. With PS5 games, you will experience the most impressive graphics ever seen on a PlayStation console. The PS5 Pro is a digital-only console and does not have a disc drive. Sign in to your PlayStationNetwork account, then visit the PlayStationStore to buy and download games. You can also add a disc drive to your PS5 Pro console if you want to play PS5 or PS4 games on Blu-ray Disc, or if you want to watch a movie or TV show on 4K Ultra HD Blu-ray Disc, Blu-ray Disc, or DVD. Features only available to PS5 games that have been Enhanced for PS5 Pro compared to PS5 games. Enhanced for PS5 Pro benefits are specific to each game.',
    discount: 17,
    image: '/images/playstation/Sony-PlayStation-5-Pro,PS5-avec-1-Manette-Sans-Fil-DualSense,Couleur:Blanche/Sony-PlayStation-5-Pro-1.jpg',
    image1: '/images/playstation/Sony-PlayStation-5-Pro,PS5-avec-1-Manette-Sans-Fil-DualSense,Couleur:Blanche/Sony-PlayStation-5-Pro-2.jpg',
    image2: '/images/playstation/Sony-PlayStation-5-Pro,PS5-avec-1-Manette-Sans-Fil-DualSense,Couleur:Blanche/Sony-PlayStation-5-Pro-3.jpg',
    image3: '/images/playstation/Sony-PlayStation-5-Pro,PS5-avec-1-Manette-Sans-Fil-DualSense,Couleur:Blanche/Sony-PlayStation-5-Pro-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ['Featuring an enhanced GPU, advanced ray tracing, and PlayStation Spectral Super Resolution, it takes gamers to new heights.', 'Enjoy ultra-sharp picture quality on your 4K TV with AI-enhanced resolution.', 'Console Optimized: With higher and more stable refresh rates, enjoy ultra-smooth gameplay supporting both 60Hz and 120Hz displays.']
  },
  {
    id: 'PlayStation 5 Digital Edition Slim (Nordic) ',
    name: 'PlayStation-5-Digital-Edition-Slim-(Nordic) ',
    price: 611.99,
    originalPrice: 777.74,
    description: 'PlayStation 5 Digital Edition Slim (Nordic)',
    discount: 17,
    image: '/images/playstation/PlayStation-5-Digital-Edition-Slim-(Nordic)/PlayStation-5-Digital-Edition-Slim-1.jpg',
    image1: '/images/playstation/PlayStation-5-Digital-Edition-Slim-(Nordic)/PlayStation-5-Digital-Edition-Slim-2.jpg',
    image2: '/images/playstation/PlayStation-5-Digital-Edition-Slim-(Nordic)/PlayStation-5-Digital-Edition-Slim-3.jpg',
    image3: '/images/playstation/PlayStation-5-Digital-Edition-Slim-(Nordic)/PlayStation-5-Digital-Edition-Slim-4.jpg',
    category: 'playstation',
    stock: 20,
    features: ['Featuring an enhanced GPU, advanced ray tracing, and PlayStation Spectral Super Resolution, it takes gamers to new heights.', 'Enjoy ultra-sharp picture quality on your 4K TV with AI-enhanced resolution.', 'Console Optimized: With higher and more stable refresh rates, enjoy ultra-smooth gameplay supporting both 60Hz and 120Hz displays.']
  },
  {
    id: 'PlayStation 5 With Blu-Ray Disc Console (SLIM) KSA VERSION + FC25 and Two White Controllers Bundle',
    name: 'PlayStation-5-With-Blu-Ray-Disc-Console-(SLIM)-KSA-VERSION+FC25-and-Two-White-Controllers-Bundle',
    price: 600.99,
    originalPrice: 746.99,
    description: 'Slim Design - With PS5 Disc Console, players get powerful gaming technology packed inside a sleek and compact console design. Including Extra controller and FC 25',
    discount: 17,
    image: '/images/playstation/PlayStation-5-With-Blu-Ray-Disc-Console-(SLIM)-KSA-VERSION-FC25-and-Two-White-Controllers-Bundle/PlayStation-5-With-Blu-Ray-Disc-Console-1.jpg',
    image1: '/images/playstation/PlayStation-5-With-Blu-Ray-Disc-Console-(SLIM)-KSA-VERSION-FC25-and-Two-White-Controllers-Bundle/PlayStation-5-With-Blu-Ray-Disc-Console-2.jpg',
    image2: '/images/playstation/PlayStation-5-With-Blu-Ray-Disc-Console-(SLIM)-KSA-VERSION-FC25-and-Two-White-Controllers-Bundle/PlayStation-5-With-Blu-Ray-Disc-Console-3.jpg',
    image3: '/images/playstation/PlayStation-5-With-Blu-Ray-Disc-Console-(SLIM)-KSA-VERSION-FC25-and-Two-White-Controllers-Bundle/PlayStation-5-With-Blu-Ray-Disc-Console-1.jpg',
    category: 'playstation',
    stock: 20,
    features: ['Disc Edition', 'Spectral Super Resolution', 'DualSense controller', 'Digital content']
  },
  {
    id: 'SIE Sony PlayStation 5 Slim Disc with Extra Dualsense Black Controller - International Version ',
    name: 'SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version ',
    price: 533.99,
    originalPrice: 666.29,
    description: 'The PS5 model (model group - slim) is a new model that achieves a smaller size with technologies and functions that deliver the experience of the PlayStation 5. The Ultra HD Blu-ray disc drive is detachable and the internal SSD storage in the unit becomes 1TB.',
    discount: 17,
    image: '/images/playstation/SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version/SIE-Sony-PlayStation-5-Slim-Disc-1.jpg',
    image1: '/images/playstation/SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version/SIE-Sony-PlayStation-5-Slim-Disc-2.jpg',
    image2: '/images/playstation/SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version/SIE-Sony-PlayStation-5-Slim-Disc-3.jpg',
    image3: '/images/playstation/SIE-Sony-PlayStation-5-Slim-Disc-with-Extra-Dualsense-Black-Controller-International-Version/SIE-Sony-PlayStation-5-Slim-Disc-1.jpg',
    category: 'playstation',
    stock: 20,
    features: ['PS5 Slim Disc and 2 controllers will expand your gaming experience. This is a great value set that includes a controller that comes with a PS5 unit as well as an additional Black dualsense controller', 'The PS5 Slim model (model group - slim) is a new model that achieves a smaller size with technologies and functions that deliver the experience of the PlayStation 5. The Ultra HD Blu-ray disc drive is detachable and the internal SSD storage in the unit becomes 1TB ', 'PlayStation 5 Description: Play Has No Limits for new game possibilities with unleash PS5 that exceeds the limits of play. Super fast SSD dramatically improves read speed Haptic technology, adaptive trigger, and 3D audio technology deliver a dense immersive feel. And experience the new generation of amazing PlayStation titles ', 'Digital content']
  },

  // MacBook Category
  {
    id: 'macbook-pro-16',
    name: 'MacBook Pro 16"',
    price: 2299.99,
    originalPrice: 2499.99,
    description: 'Ultimate power for ultimate professionals',
    discount: 8,
    image: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image1: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image2: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image3: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    category: 'macbook',
    stock: 35,
    features: ['M3 Max chip', '32GB RAM', '1TB SSD', '16" Liquid Retina XDR']
  },
  {
    id: 'macbook-pro-14',
    name: 'MacBook Pro 14"',
    price: 1799.99,
    originalPrice: 1999.99,
    description: 'Pro performance in a portable size',
    discount: 10,
    image: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image1: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image2: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image3: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    category: 'macbook',
    stock: 40,
    features: ['M3 Pro chip', '16GB RAM', '512GB SSD', '14" Liquid Retina XDR']
  },
  {
    id: 'macbook-air-15',
    name: 'MacBook Air 15"',
    price: 1299.99,
    originalPrice: 1499.99,
    description: 'Incredibly thin. Seriously powerful.',
    discount: 13,
    image: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image1: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image2: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image3: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    category: 'macbook',
    stock: 60,
    features: ['M3 chip', '16GB RAM', '512GB SSD', '15" Liquid Retina']
  },
  {
    id: 'macbook-air-13',
    name: 'MacBook Air 13"',
    price: 999.99,
    originalPrice: 1199.99,
    description: 'The most affordable MacBook Air',
    discount: 17,
    image: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image1: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image2: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    image3: 'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg',
    category: 'macbook',
    stock: 85,
    features: ['M3 chip', '8GB RAM', '256GB SSD', '13.6" Liquid Retina']
  }
];
